### ISSUE TITLE
Code Editing (Ace) accets macosx fail

### ISSUE THREAD

**Issue by carperfer** [firebase/firepad#114]
Code Editing (Ace) accets "áéíóú" on macosx fails, delete text:
Ex word:
compártelo
you write:
comp
ártelo ("comp" are deleted)
A video with the fail. It's used in shiftedit with Code Editing (Ace) "multiple users".
https://www.dropbox.com/s/rx56sii9oi5oq2z/test.mov

**Comment by hugorodrigues** [comment]
+1

**Comment by mikelehen** [comment]
When I experiment on the firepad "Code Editing (Ace)" demo here (https://firepad.io/examples/) I get a different (although also broken) behavior.

When I type "compártelo" it ends up duplicating the a so I get "compaártelo".  But this is also the same behavior I get with the pure Ace editor (https://ace.c9.io/build/kitchen-sink.html) with no firepad.

So I'm not sure if there's a firepad issue here?  I'm closing for now.  If you believe there to be a firepad-specific issue (rather than an issue with ShiftEdit or Ace itself), let me know.  Thanks!
