### ISSUE TITLE
What does `RTCMADAPTER` signify?

### ISSUE THREAD

**Issue by arunthampi** [firebase/firepad#164]
I'm trying to determine whether a CodeMirror "change" was generated by a local action or a remote action, and by observing logs it looks like if `change.origin` is either `== 'RTCMADAPTER'` or `match(/cmrt-\d+/)` then its a remote change. Is that a correct deduction?

**Comment by mikelehen** [comment]
Hey Arun,

It's actually hard/impossible to tell from the events.

First, a bit of background:
* CodeMirror is the core editor firepad is based on (as I'm sure you know).
* To add rich-text capabilities, firepad has a layer on /top/ of CodeMirror called RichTextCodeMirror.  This layer maintains an additional data structure tracking all of the rich text annotations on top of the core text that CodeMirror is storing.  To do that, it both makes edits to the underlying CodeMirror instance and consumes the events that CodeMirror produces on each change.
* In order for RichTextCodeMirror to identify its own CodeMirror edits, it marks them as cmrt-XX where XX is an internal change id.
* RichTextCodeMirrorAdapter is a component that sits between RichTextCodeMirror and the OT system.  It's basically responsible for taking changes from RichTextCodeMirror and turning them into OT operations to be sent to everybody else, and taking OT operations from everybody else and turning them into RichTextCodeMirror edits.

So basically, anything that goes through RichTextCodeMirror is going to have a "cmrt-XX" origin.  This will /mostly/ be edits coming from RichTextCodeMirrorAdapter (i.e. remote users' edits), but there are other richtext-related edits that go through RichTextCodeMirrorAdapter too (e.g. if you insert an image or call firepad.setHtml() or firepad.insertText(), etc.).  So some cmrt-XX edits will not be remote edits.

I don't think you would ever see RTCMADAPTER as the origin but we do use that internally.  It's a bit complicated, but basically:
1. When you edit the RichTextCodeMirror (e.g. we got a remote edit and are applying it to RichTextCodeMirror), we set the origin as RTCMADAPTER.
2. Inside RichTextCodeMirror, we convert the edit to a CodeMirror edit and set the origin to cmrt-XX.
3. RichTextCodeMirror will get a 'change' event from CodeMirror and will see that the origin is cmrt-XX.  It'll then look up the id, and discover that the original origin was RTCMADAPTER.
4. RichTextCodeMirror will now raise its own event with origin RTCMADAPTER.

What this means is if you subscribed to the 'change' events on RichTextCodeMirror (instead of on CodeMirror directly), you could just check the origin and if it's RTCMADAPTER you'd know it was a remote event.

But there are a couple obstacles:
1) RichTextCodeMirror isn't publicly exposed.  You can get at it with firepad.richTextCodeMirror_ but this isn't really supported (I might change the name of that variable in the future).
2) The RichTextCodeMirror 'change' events are a bit different than CodeMirror ones.  In particular, it deals with absolute offsets into the text instead of line/col positions.

Still, this may be your best option.

Sorry this is so long and probably confusing but maybe this gives you some ideas.  If this is blocking you, let me know.  I could publicly expose richTextCodeMirror on the firepad object or perhaps tweak the way we assign origins so that you could distinguish at the CodeMirror-level which are remote or not.

Hope this helps!

**Comment by arunthampi** [comment]
Thanks for the explanation Michael. I'm definitely seeing origin == `RTCMADAPTER` This happens when the text is deleted remotely. When text is inserted remotely, I see a `cmrt-xx`. (All "local" changes has its origin set to either "+input" or "+delete".

For my purposes, checking for RTCMADAPTER or cmrt-xx seems to be working now, although I'm in the process of doing more testing. A documentated way to detect the source of a change will probably be useful though, for e.g. for keeping other metadata such as bookmarks, markers, etc. in sync.

**Comment by ThariqS** [comment]
@arunthampi I have the same goal, did you ever end up finding any edge cases with that method?

**Comment by arunthampi** [comment]
@ThariqS the project that i was working on is no longer active so I haven't run into any edge cases, no :(
