### ISSUE TITLE
TAB does not seem to work in Rich Text mode

### ISSUE THREAD

**Issue by q-state** [firebase/firepad#172]
Hi

The demo page with the CodeMirror RichText version does not seem to support tabs. 

The JavaScript CodeMirror version does with the cm-tab element.

Is there a rich-text workaround or fix for this?

**Comment by mikelehen** [comment]
Thanks.  I fixed the examples by reordering the firepad.css include, but it shouldn't matter, so I've logged #173 to fix the underlying issue.

**Comment by q-state** [comment]
Thanks Mike.

If I wanted to support TABs in the middle of a line, would I need to implement something that inserted fixed width spans or something?

**Comment by mikelehen** [comment]
Yeah, you could make it insert spaces (or an actual tab character or whatever) instead of indenting the line.

FYI- We bind the 'Tab' key here: https://github.com/firebase/firepad/blob/master/lib/firepad.js#L477 so that it calls our indent() code here: https://github.com/firebase/firepad/blob/master/lib/firepad.js#L340

**Comment by q-state** [comment]
Awesome, thanks so much Mike.

**Comment by static-void** [comment]
Hi, I have this issue on the demo page, I cannot add tabs in the middle of a line. Is this a user error?
