### ISSUE TITLE
Brief overview of how everything works...

### ISSUE THREAD

**Issue by knpwrs** [firebase/firepad#220]
Is there a brief overview available of how everything works? My understanding of operational transformation is that a server transforms operations from clients such that all clients end up with the same result. Firebase, to the best of my knowledge, does not allow for custom server-side logic. So I dug around a little bit and found [`transaction()`](https://www.firebase.com/docs/web/api/firebase/transaction.html) which seems to make sense but I have some questions.

1. Is the client essentially just transforming its operations in the event that the server has changes that the client doesn't? And then just retrying?
2. If so, how performant is this compared to what I'll call "classical" operational transformation, where the server does the transformation as opposed to the client? If there are a bunch of clients are they all stuck waiting turns to perform writes?
3. Or, if not so, what am I missing?

**Comment by mikelehen** [comment]
I haven't really written a good overview of our OT approach :-( but you can
find a very short summary in my reply here
<https://github.com/firebase/firepad/issues/163> but you're on the right
track.  To answer your questions:

   1. Yes.

   2. Ignoring contention (which I'll get to in a second), the amount of
   computational work is the same but it moves the work of transforming
   operations to the client instead of the server, which means the server has
   to do much less work.  And since the server is going to be the bottleneck
   we care about, that could be seen as an advantage.

   The big potential downside is that clients could have to retry
   operations, and theoretically clients could become starved if the OT
   history is rapidly changing such that they can't successfully append their
   operation to the end.  In practice I've never seen / heard of this
   happening with firepad though.

   One thing that works in your favor is that a client will only ever have
   a single operation outstanding and will "batch" all subsequent edits into a
   new operation.  So each time a client retries, it'll be sending an
   operation that represents all edits that have been made, and so if the
   client can successfully apply that operation, it'll be 100% up-to-date (you
   won't end up with a "backlog" of operations you're trying to apply).

   In general, for normal use cases I think the user experience of
   collaboratively editing a doc will probably break down well before you hit
   contention / starvation issues.

Hope this helps!
-Michael

**Comment by knpwrs** [comment]
Cool stuff. Thanks.
