### ISSUE TITLE
setHtml (parseHtml) is very slow on bigger documents

### ISSUE THREAD

**Issue by kofifus** [firebase/firepad#229]
see http://jsfiddle.net/du9rv2rg/

on my machine loading took 40 sec ! getHtml took 40ms but setHtml took 20 sec !

slow setHtml becomes a big issue on rich text paste.

any ideas of why this is so slow or how it can be done better ?

Thx!

(note pls leave the long text on the pad so others can test as well)

**Comment by amanuel2** [comment]
It took me about 1second or lower.. What computer are you using?

**Comment by kofifus** [comment]
Are you sure ? for both loading and setHtml() ? that is very strange.

I am using a business model laptop with an i5 CPU Iit can't be a CPU problem. 

My internet may be much slower than yours. I assumed setHtml does not go to the network but maybe that's wrong ?

**Comment by amanuel2** [comment]
Hmm.... You can always do a workaround :)  firepad.setText(Text you want to be set.');   If you are setting text

**Comment by mikelehen** [comment]
Neither getHtml or setHtml go to the network.  For me, setHtml took 17s when I tried it awhile ago, which is inline with @kofifus's report.  But I just tried it now and it was super fast because the firepad instance is now empty for some reason. :-)

Anyway, I'm not super shocked it's slow with that amount of rich text.  Firepad's data structure for dealing with rich-text is pretty inefficient.  I'd like to improve it at some point, but it hasn't been a priority.

FWIW, I would imagine that the setHtml() time is almost identical to the initial load time, since it's the rich-text that's the problem, not setHtml() per se.

**Comment by kofifus** [comment]
Thx Michael !

I have updated the fiddle http://jsfiddle.net/du9rv2rg/ to a setHtml with 1000 lines to facilitate testing. 

Now slow is one thing but over 20 seconds to insert 1000 lines ? can you give some pointers as to where do you think the main issue is ?

**Comment by mikelehen** [comment]
I have some ideas, but best bet is to use the chrome profiler to find out for sure where the time is being spent. :-)

**Comment by danielschwartz** [comment]
@mikelehen just wanted to point out that when inserting html (via copy/paste) using setHtml it seems to be slower for me. My only explanation of this is that doing setHtml is forcing a draw of every line that CodeMirror is inserting, whereas the initial load is only drawing what is shown in the viewport.

**Comment by mikelehen** [comment]
@danielschwartz Thanks for the note.  That is indeed interesting and suggests there's probably *some* low-hanging fruit here, like maybe batching the setHtml work in a CodeMirror operation or something.

**Comment by kofifus** [comment]
submitted https://github.com/firebase/firepad/pull/230

see test in: http://jsfiddle.net/wwzkbkk4/

**Comment by kofifus** [comment]
solved with https://github.com/firebase/firepad/commit/d0459a83129e0e9e16516faa169f3b3e8f381b45
