### ISSUE TITLE
add initial revisions to undo history

### ISSUE THREAD

**Issue by kofifus** [firebase/firepad#266]
I need help implementing adding the initial revisions (since last checkpoint) into the undo history.

in FirebaseAdapter.prototype.handleInitialRevisions_ I have
   `this.document_ = this.document_.compose(revision.operation);`

I think this would be the place to add revision.operation to the undo history

But I don't know how to proceed ? the whole undo thing is quite complicated ...

Any help ?

**Comment by mikelehen** [comment]
To be honest, this probably isn't very straightforward to do and will probably result in a weird / broken user experience since 1) the number of revisions since the last checkpoint will be an arbitrary number between 0 and 99, and 2) the revisions will come from different users and so you'll be undoing operations done by different users.

If you really want to try, I think you'd need to somehow have firebaseAdapter raise an event or similar with the initial revisions, which then you handle at a higher level (firepad.js perhaps) and pass to EditorClient's onChange method (or similar) so that it gets added to the undo stack.  But there will probably be complications.

**Comment by kofifus** [comment]
Thx Michael,

I think this will be an awesome feature so I think I will give it a go sometime ..

Yes I will have to go before the checkpoint if I want to always add the N last revisions to the undo stack ... that shouldn't be too hard ..

Also  undoing operations done by different users is find as this is the way the document was built

what I'm not sure is if I need to massage the revision.operation from handleInitialRevisions_ in some way before passing it to the undo manager ? does it need to be reveresd or wrapped as I've seen done in some places ?

thx!
