### ISSUE TITLE
initial call to monitorHistoryStartingAt_

### ISSUE THREAD

**Issue by kofifus** [firebase/firepad#267]
in https://github.com/firebase/firepad/blob/master/lib/firebase-adapter.js#L219

when the editor loads, we first get the last checkpoint and then call monitorHistoryStartingAt_ that loads all the revisions since the checkpoint using `self.firebaseOn_(historyRef, 'child_added', function(revisionSnapshot) {`

As far as I understand this will loads the revisions one by one which in the worst case mean 99 separate callbacks ? ...

Wouldn't be significantly more efficient to load the initial revisions-since-last-checkpoint with a single query and iterate over them with forEach ?

firepad initial loading is slow and I wonder if this kind of change will make a big difference ?

**Comment by mikelehen** [comment]
Sorry, but that won't make any difference.  Although it is 99 callbacks, Firebase will read all of the data with a single request (the exact same request that would happen if we did an .on('value' ...) or whatever.  And once the data is loaded, 99 callbacks is not very expensive.

Have you tried profiling it?  I think it's more likely slow loading is due to rich-text formatting, perhaps in a long document.

**Comment by kofifus** [comment]
ah great :)
