### ISSUE TITLE
Add monaco-editor support

### ISSUE THREAD

**Issue by pranjaltale16** [firebase/firepad#297]
I was trying to hack around adding the [monaco-editor](https://github.com/Microsoft/monaco-editor) support in firepad. I tried to follow ace-adapter.coffee. [Here](https://github.com/pranjaltale16/firepad/blob/monaco/lib/monaco-adapter.js) is the adapter for monaco. I'm facing some issues in this. 
How to add `detach` and `setOtherCursor` functionality for monaco?
How `trigger` works?
Also, could you please have a look at the adapter once and suggest me the changes on the work that I've done till now?

Thanks!

**Comment by pranjaltale16** [comment]
@mikelehen, could you please help me with this?

**Comment by pranjaltale16** [comment]
I need a little help in debugging to proceed further.
Whenever the `onChange` event is called, it calls `operationFromMonacoChange` to generate TextOperations. Operations are failing [here](https://github.com/firebase/firepad/blob/master/lib/firebase-adapter.js#L128). `this.document_.targetLength` is not getting updated.
I'm unable to figure it out how `document_` is updated there are  several instances which calls for revision of the same, but not sure which one and how it gets updated. Could you help me with this?

Thank you for explaining the functioning of trigger and callbacks. :smile:

For ref, a snap of traceback of calls when `onChange` is called
![screenshot from 2018-05-18 15-55-44](https://user-images.githubusercontent.com/15308785/40230446-20b6c924-5ab5-11e8-96f1-ad9d3d6c5761.png)
.

**Comment by pranjaltale16** [comment]
Done with the above issue. The issue was the index value, for monaco-editor, it starts with 1.

**Comment by pranjaltale16** [comment]
@mikelehen I'm almost done with the adapter. Mainly two things are left. First is to update the detach function(I'll try to look around this).

Second is to update `applyOperationsFromMonaco` for a [particular case](https://github.com/pranjaltale16/firepad/blob/monaco/lib/monaco-adapter.js#L88). The bug is when we select some text and tries to replace it with some other text. In case of ace-editor, it emits two different events for the same. So that is handled easily in ace-adapter but in case of monaco, it emits only a single event for both, having the output of the form. 
![screenshot from 2018-05-21 18-59-20](https://user-images.githubusercontent.com/15308785/40310216-abdf1738-5d29-11e8-81ea-884e90bd77ba.png)

The problem occurs when we try to add the text(using copy paste) of length more than the length remaining(till the end from that point). I tried to follow codemirror-adapter but this problem is still there. I need to update [these](https://github.com/pranjaltale16/firepad/blob/monaco/lib/monaco-adapter.js#L89) text operations to get it working, could you please help me with this?
Once done, I can push the PR for review.

**Comment by mikelehen** [comment]
Without digging into this too much, I suspect you shouldn't exactly overwrite text and restLength here: https://github.com/pranjaltale16/firepad/blob/monaco/lib/monaco-adapter.js#L76 in this case since you have both an insert operation and a delete operation and they are inserting and deleting different text and the restLength is going to be different for each one (the delete will need to shrink the restLength but the insert will not).  But I haven't dug into this too much.  So I'm not sure exactly what you need to do to fix it.

**Comment by pranjaltale16** [comment]
In case of monaco, it doesn't give you the text you've replaced, while the other text editors provide the same. So that's why in order to the text that has to be replaced I modified the text on line 76.

The problem is in the edge case only. Suppose the content of the editor is `abcdef`, now if we try to replace `d` by any string of length greater than 2, it breaks. so if we try to replace any part of the string by the string of length greater than the remaining length then the problem occurs. I know it's hard to explain the problem this way. If you've time kindly let me know. I will share the dist and HTML embedded with firebase creds so that you can look into it.

**Comment by mikelehen** [comment]
Unfortunately I don't have a lot of time.  I just noticed you have text / text_m to differentiate the added / removed text.  That's good (though I would name them more clearly).  But I think you also need a different restLength calculation for iop and dop.  Because depending on the lengths of the inserted and deleted text, the resulting remaining length will be different.

**Comment by pranjaltale16** [comment]
Sure, I will look around that. Could you please explain just one thing, What exactly is restLength is and how can I think of calculating it?

**Comment by pranjaltale16** [comment]
Why are operations always sent in a pair from `applyOperationFromEditor` and what is the role of the second operation? Can I send 4 operations together? Initial two will be for deletion of the text and next 2 will be for the addition. If yes, what should be the order?

**Comment by mikelehen** [comment]
I haven't dug into this in a long time, but if memory serves right it's to allow undo/redo to work correctly.  Collaborative editing completely breaks the editor's internal undo/redo functionality (you'd end up undoing random edits from other users and any time somebody else makes an edit it'd clear your redo stack).  So firepad has to implement its own undo/redo.  In order to correctly undo and redo we need both the operation representing the edit and the "undo" operation representing the inverse of the edit.

**Comment by pranjaltale16** [comment]
I'm trying to solve those edge cases, but still unable to figure where exactly the problem is.
What all is required apart from `monaco-adapter.js` to make a PR, like tests, etc?

**Comment by pranjaltale16** [comment]
Done with the implementation. :smile:

**Comment by pranjaltale16** [comment]
I think it's done. I'm closing this.
